name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Dependencies
      run: |
        cd src
        composer install -v --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env
      run: |
        cd src
        if [ ! -f .env ]; then cp .env.example .env; fi

    - name: Generate key
      run: |
        cd src
        php artisan key:generate

    - name: Set Directory Permissions
      run: |
        cd src
        chmod -R 777 storage bootstrap/cache

    - name: Create SQLite Database
      run: |
        cd src
        mkdir -p database
        touch database/database.sqlite

    - name: Run Migrations
      run: |
        cd src
        php artisan migrate --force

    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        cd src
        php artisan test
