name: Laravel

on:
  push:
    branches: [ "shop" ]
  pull_request:
    branches: [ "shop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: portforio
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Install Composer Dependencies
      run: |
        cd src
        composer install --prefer-dist --no-progress --no-scripts
    - name: Set up environment
      run: |
        cd src
        cp .env.example .env
    - name: Generate application key
      run: |
        cd src
        php artisan key:generate
    - name: Adjust permissions
      run: |
        cd src
        chmod -R 777 storage bootstrap/cache
    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h"127.0.0.1" --silent; then
            break
          fi
          echo "Waiting for MySQL..."
          sleep 1
        done
    - name: Build Assets with Vite
      run: |
        cd src
        npm install
        npm run build
    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_DATABASE: portforio
        DB_USERNAME: root
        DB_PASSWORD: root
      run: |
        cd src
        php artisan migrate --force
    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_DATABASE: portforio
        DB_USERNAME: root
        DB_PASSWORD: root
      run: |
        cd src
        php artisan test
