name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: portforio
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          MYSQL_PASSWORD: root  # MySQLユーザーのパスワードを設定
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # 必要に応じてNode.jsのバージョンを変更
    - name: Install Node.js dependencies
      run: |
        cd src
        npm install
    - name: Build assets
      run: |
        cd src
        npm run build
    - name: Install PHP dependencies
      run: |
        cd src
        composer install -v --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Copy .env
      run: |
        cd src
        php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Generate key
      run: |
        cd src
        php artisan key:generate
    - name: Directory Permissions
      run: |
        cd src
        chmod -R 777 storage bootstrap/cache
    - name: Execute migrations
      run: |
        cd src
        php artisan migrate --force
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: portforio
        DB_USERNAME: root
        DB_PASSWORD: root  # 環境変数にパスワードを追加
      run: |
        cd src
        php artisan test
