name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Copy .env
      run: cp .env.example .env
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Create SQLite database
      run: |
        mkdir -p src/database
        touch src/database/database.sqlite
    - name: Set up .env for SQLite
      run: |
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=$(pwd)/src/database/database.sqlite" >> .env
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run migrations
      run: php artisan migrate --force
    - name: Run tests
      run: php artisan test
